services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "-q", "SELECT 1"]
      interval: 1s
      timeout: 10s
      retries: 30
  migrations:
    depends_on:
      clickhouse:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.scrape
    entrypoint: []
    command:
      - python3
      - /app/migrations.py
    volumes:
      - ./:/app:ro
    environment:
      - CLICKHOUSE_HOST=clickhouse
  app:
    depends_on:
      migrations:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 10s
      retries: 30
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./app.py:/app.py:ro
      - ./templates:/templates:ro
    environment:
      - CLICKHOUSE_HOST=clickhouse
    ports:
      - "5001:5000"
  scrape:
    platform: linux/x86_64
    depends_on:
      app:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.scrape

    volumes:
      - ./:/app:ro
    environment:
      - CLICKHOUSE_HOST=clickhouse

